### ISSUE TITLE
setDecayMode() always sets decay mode to 000

### ISSUE THREAD

**Issue by benjii33** [pololu/drv8434s-arduino#2]
In the function `setDecayMode()`, the `mode` argument is shifted left by 8 bits before being OR'ed with the current register value, resulting in the `DECAY` bits being cleared no matter what the initial `mode` argument was. In addition to preventing the DecayMode from being set to anything other than the default `SmartTuneRippleControl` or `SLOW:SLOW`, this also breaks stall detection, which requires the decay mode set to the default. Users who think they are confirming that the decay mode is properly set are actually setting it to another mode, preventing the feature from working.

```
void setDecayMode(DRV8434SDecayMode mode)
{
    ctrl2 = (ctrl2 & 0b11111000) | (((uint8_t)mode & 0b111) << 8);
    writeCachedReg(DRV8434SRegAddr::CTRL2);
}
```

**Comment by kevin-pololu** [comment]
Thanks for pointing this out!
